#################################
# paths.conf is part of Barleymap web app.
# Copyright (C) 2017  Carlos P Cantalapiedra.
# (terms of use can be found within the distributed LICENSE file).
#################################
# App absolute path
app_path /var/www/html/barleymap/
# Relative paths to auxiliary apps
genmap_path app_aux/
split_blast_path app_aux/
# Absolute paths to temporary and datasets folders
tmp_files_path /var/www/html/barleymap/tmp_files
datasets_path /home/contrera/barleymap/datasets/
annot_path /home/contrera/barleymap/datasets_annotation/
maps_path /home/contrera/barleymap/maps/
########### Aligners
# Blast
blastn_app_path /home/contrera/ncbi-blast-2.2.27+/bin/blastn
blastn_dbs_path /data/barleymap/blast_dbs/
# GMAP
gmap_app_path /usr/local/bin/gmap
gmap_dbs_path /data/barleymap/gmap_dbs/
gmapl_app_path /usr/local/bin/gmapl
# miniprot (not used feb2025)
miniprot_app_path /home/contrera/miniprot-0.13/miniprot
miniprot_dbs_path /data/barleymap/miniprot_dbs/
# align2graph
align2graph_app_path /home/contrera/align2graph.py 
align2graph_dbs_path /nfs/PHG_barleymap/graphs/
# HS-Blastn, not used
hsblastn_app_path /home/contrera/bin/hs-blastn-0.0.5+/hs-blastn-src/hs-blastn
hsblastn_dbs_path /data/barleymap/hsblastn_dbs/
########### Other
citation Sarria_J,_Amhal_H,_Ramirez_CJ,_Igartua_E,_Casas_AM,_Contreras-Moreira_B(2026)_A_pangenome-graph_approach_for_mapping_and_imputing_barley_sequences._bioRxiv_2026.08.06.741139,_doi:10.64898/2026.08.06.741139
stdalone_app https://github.com/Cantalapiedra/barleymap 

