#################################
# paths.conf is part of Barleymap web app.
# Copyright (C) 2017  Carlos P Cantalapiedra.
# (terms of use can be found within the distributed LICENSE file).
#################################
# App absolute path
app_path /var/www/html/barleymap/
# Relative paths to auxiliary apps
genmap_path app_aux/
split_blast_path app_aux/
# Absolute paths to temporary and datasets folders
tmp_files_path /var/www/html/barleymap/tmp_files
datasets_path /home/contrera/barleymap/datasets/
annot_path /home/contrera/barleymap/datasets_annotation/
maps_path /home/contrera/barleymap/maps/
########### Aligners
# Blast
blastn_app_path /home/contrera/ncbi-blast-2.2.27+/bin/blastn
blastn_dbs_path /data/barleymap/blast_dbs/
# GMAP
gmap_app_path /usr/local/bin/gmap
gmap_dbs_path /data/barleymap/gmap_dbs/
gmapl_app_path /usr/local/bin/gmapl
# miniprot (not used feb2025)
miniprot_app_path /home/contrera/miniprot-0.13/miniprot
miniprot_dbs_path /data/barleymap/miniprot_dbs/
# align2graph
align2graph_app_path /home/contrera/align2graph.py 
align2graph_dbs_path /nfs/PHG_barleymap/
# HS-Blastn, not used
hsblastn_app_path /home/contrera/bin/hs-blastn-0.0.5+/hs-blastn-src/hs-blastn
hsblastn_dbs_path /data/barleymap/hsblastn_dbs/
########### Other
citation Cantalapiedra_CP,_Boudiar_R,_Casas_AM,_Igartua_E,_Contreras-Moreira_B._BARLEYMAP:_physical_and_genetic_mapping_of_nucleotide_sequences_and_annotation_of_surrounding_loci_in_barley._Mol_Breeding_(2015)_35:13_DOI_10.1007/s11032-015-0253-1
stdalone_app https://github.com/Cantalapiedra/barleymap 
